INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Infectious and Parasitic', NULL);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Viral infections', 1);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Acquired immunodeficiency syndrome (AIDS)', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Other', 1);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Acute Flaccid Paralysis (excluding Acute poliomyelitis)', 4);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Acute encephalitis (excluding JE and WNE)', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Acute poliomyelitis', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Parasitic infections', 1);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Amebiasis', 8);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Bacterial infections', 1);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Anthrax', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Avian influenza (exclud. Avian influenza both H5N1 and H7N9)', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Avian influenza H5N1', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Avian influenza H7N9', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Botulism', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Brucellosis', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Carcinomas', NULL);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Systemic/General', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'C00-C96', 18);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'C00-C96 D00-D09', 18);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Urogenital system', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'C53-C55', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Carbapenem-resistant Enterobacterales infection', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Carbapenem-resistant enterobacteriaceae infection', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Chikungunya fever', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Cholera', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Mycotic infections', 1);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Coccidioidomycosis', 27);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Congenital rubella syndrome', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Creutzfeldt-Jakob disease', 4);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Crimean-Congo hemorrhagic fever', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Cryptosporidiosis', 8);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Dengue fever', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Diphtheria', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Disseminated cryptococcal infection', 27);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Eastern equine encephalitis', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Echinococcosis', 8);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Enterohemorrhagic Escherichia coli infection', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Epidemic typhus', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Giardiasis', 8);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Glanders', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Hantavirus pulmonary syndrome', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Hemorrhagic fever with renal syndrome', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Hendra virus infection', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Hepatitis A', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Hepatitis E', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Digestive system', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Hepatocelulárny karcinóm', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Herpes B virus infection', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Invasive haemophilus influenzae infection', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Invasive meningococcal infection', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Invasive streptococcal pneumoniae infection', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Japanese encephalitis', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Japanese spotted fever', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Karcinóm in situ hrubého čreva', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Karcinóm in situ krčka maternice', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Karcinóm in situ močového mechúra', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Karcinóm in situ pažeráka', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Karcinóm prsníka in situ', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Karcinómy in situ dolnej časti tráviaceho traktu', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Respiratory system/Thorax', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Karcinómy in situ dolných dýchacích ciest', 61);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Karcinómy in situ hrubého čreva a konečníka', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Karcinómy kože in situ', 18);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Kyasanur forest disease', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Lassa fever', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Legionellosis', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Leptospirosis', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Lymphatic and Hemopoietic', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Leukemia', 69);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Lyme disease', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Lyssavirus infection (excluding rabies)', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Malaria', 8);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Marburg disease', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Measles', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Melanóm a iné zhubné nádory kože', 18);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Melioidosis', 27);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Middle East Respiratory Syndrome Coronavirus', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Monkeypox / Mpox', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Multiple drug-resistant Acinetobacter infection', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Nipah virus infection', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Omsk hemorrhagic fever', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Paratyphoid fever', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Pertussis', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Plague', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Psittacosis', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Q fever', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Rabies', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Rakovina vaječníkov a vajíčkovodov', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Relapsing fever', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Rift valley fever', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Rocky mountain spotted fever', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Rubella', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Scrub typhus (Tsutsugamushi disease)', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Severe Acute Respiratory Syndrome (SARS)', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Severe Fever with Thrombocytopenia Syndrome (SFTS)', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Severe invasive streptococcal infections (TSLS)', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Shigellosis', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Smallpox', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'South American hemorrhagic fever', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Syphilis', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Tetanus', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Tick-borne encephalitis', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Tuberculosis', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Tularemia', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Typhoid fever', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Vancomycin-resistant Enterococcus infection', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Vancomycin-resistant S. aureus infection', 10);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Varicella (hospitalized case)', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Venezuelan equine encephalitis', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Viral hepatitis (excluding hepatitis A and E)', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'West Nile fever', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Western equine encephalitis', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Yellow fever', 2);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubná imunoproliferatívna choroba', 69);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Nervous system', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubné nádoby centrálneho nervového systému', 116);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubné nádoby močovej sústavy', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubné nádoby pery ústnej dutiny a hltana', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubné nádoby s pôvodom alebo s predpokladaným pôvodom z lymfatického hemopoetického a príbuzného tkaniva', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubné nádoby žlčníka a zhubné nádoby iných a bližšie neurčených častí žlčových ciest', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor hrtana', 61);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor hrubého čreva, rekto-sigmoídového spojenia a konečníka', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor konečníka', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor krčka maternice', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor močového mechúra', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor myometria', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor pažeráka', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor podžalúdkovej žľazy', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor priedušnice priedušiek a pľúc', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor prostaty', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor prsníka', 21);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Endocrine system', 17);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor štítnej žľazy', 133);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zhubný nádor žalúdka', 47);
INSERT INTO sickness (sickness_label, id_parent_sickness) VALUES ( 'Zika virus infection', 2);
